# Generated by Django 6.0.7 on 2026-07-10 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_agentprofile_id_alter_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='must_change_password',
            field=models.BooleanField(default=False, help_text="True tant que l'utilisateur n'a pas changé le mot de passe temporaire généré à la création de son compte. Forcé à True explicitement uniquement dans RegisterView/ManagerCreateView/import Excel (comptes créés avec un mot de passe généré) — les comptes créés autrement (createsuperuser, seed_data, admin Django) restent à False, considérés déjà onboardés."),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_verifie',
            field=models.BooleanField(default=True, help_text='False uniquement pour les comptes créés avec un mot de passe temporaire (RegisterView/ManagerCreateView/import Excel), qui doivent vérifier leur téléphone à la première connexion. True par défaut pour tous les autres comptes (déjà onboardés).'),
        ),
    ]