# Generated by Django 6.0.3 on 2026-04-15 12:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tasks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RapportExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_rapport', models.CharField(choices=[('completion', 'Tâche terminée'), ('non_execution', 'Non exécutée')], default='completion', max_length=20)),
                ('commentaire', models.TextField(blank=True, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='rapports/photos/%Y/%m/')),
                ('raison_non_execution', models.TextField(blank=True, null=True)),
                ('categorie_raison', models.CharField(blank=True, choices=[('absence', 'Absence client'), ('indisponibilite', 'Indisponibilité accès'), ('materiel', 'Problème matériel'), ('meteo', 'Conditions météo'), ('urgence', 'Urgence autre'), ('autre', 'Autre')], max_length=50, null=True)),
                ('date_soumission', models.DateTimeField(auto_now_add=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rapports', to=settings.AUTH_USER_MODEL)),
                ('sous_tache', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rapports', to='tasks.soustache')),
                ('tache', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rapports', to='tasks.tache')),
            ],
            options={
                'ordering': ['-date_soumission'],
            },
        ),
    ]
