# Generated by Django 6.0.6 on 2026-07-07 07:16

import django.core.validators
import reports.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rapportexecution',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='rapports/photos/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp']), reports.validators.valider_taille_photo]),
        ),
    ]