# Generated by Django 5.2.15 on 2026-07-09 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_alter_rapportexecution_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rapportexecution',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
