# Generated by Django 6.0.6 on 2026-07-06 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tache',
            name='adresse_complet',
            field=models.CharField(blank=True, help_text="Adresse complète du lieu d'intervention", max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tache',
            name='gps_latitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text="Latitude du lieu d'intervention", max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='tache',
            name='gps_longitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text="Longitude du lieu d'intervention", max_digits=9, null=True),
        ),
    ]