# Generated by Django 6.0.6 on 2026-07-07 00:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_tache_adresse_complet_tache_gps_latitude_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tache',
            name='donnees_excel',
            field=models.JSONField(blank=True, default=dict, help_text="Colonnes additionnelles issues du fichier Excel d'origine"),
        ),
        migrations.CreateModel(
            name='ImportLot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_fichier', models.CharField(max_length=255)),
                ('toutes_colonnes', models.JSONField(blank=True, default=list)),
                ('colonnes_obligatoires', models.JSONField(blank=True, default=list)),
                ('colonnes_visibles_mobile', models.JSONField(blank=True, default=list)),
                ('mapping', models.JSONField(blank=True, default=dict, help_text="Ex: {'agent': 'Nom Agent', 'titre': 'Intitulé tâche'}")),
                ('date_import', models.DateTimeField(auto_now_add=True)),
                ('nombre_taches_creees', models.PositiveIntegerField(default=0)),
                ('nombre_erreurs', models.PositiveIntegerField(default=0)),
                ('importe_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='imports_excel', to=settings.AUTH_USER_MODEL)),
                ('semaine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imports_excel', to='tasks.semaine')),
            ],
            options={
                'ordering': ['-date_import'],
            },
        ),
        migrations.AddField(
            model_name='tache',
            name='lot_import',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='taches', to='tasks.importlot'),
        ),
    ]